services:
  postgres:
    image: postgres:16.1
    environment:
      POSTGRES_DB: shareit
      POSTGRES_USER: shareit
      POSTGRES_PASSWORD: shareit
    ports:
      - "5432:5432"

  shareit-server:
    build:
      context: .
      dockerfile: server/Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/shareit
      SPRING_DATASOURCE_USERNAME: shareit
      SPRING_DATASOURCE_PASSWORD: shareit
    ports:
      - "9090:9090"
    depends_on:
      - postgres

  shareit-gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    environment:
      SERVER_PORT: 8080
      SHAREIT_SERVER_URL: http://shareit-server:9090
    ports:
      - "8080:8080"
    depends_on:
      - shareit-server
